### ISSUE TITLE
does not appear to work if you use google account for openAI login

### ISSUE THREAD

**Issue by shusenl** [teavver/gpt-4-vision-api-wrapper#1]
I'm wondering if that is the case and if is there a way around it, thanks!

**Comment by teavver** [comment]
you're correct, there's no google login support yet. this is a good feature and i'll definitely plan to add it soon. please be aware that for automation purposes, using a google account for login will require 2FA to be disabled

**Comment by teavver** [comment]
first-time login using google account should be available now. please try it out and let me know if it works as expected

**Comment by teavver** [comment]
it's because of the user-agent the script is using - i set the default to chrome browser running on windows 10. you can change it if you wish. i'm glad it works, enjoy!
